name = "iso_8859"
version = "2.0.0"
description = "Gleam library to decode ISO/IEC 8859 binary data into a native string."
licences = ["MIT"]
repository = { type = "github", user = "richard-viney", repo = "iso_8859" }
links = [
    { title = "Website", href = "https://github.com/richard-viney/iso_8859" },
]

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"

[javascript]
typescript_declarations = true
